name: Node
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
permissions: read-all
env:
  PUBLIC_ROWS: 4
  PUBLIC_COLUMNS: 4
  ABLY_API_KEY: 'ABC123'
  PUBLIC_ABLY_CHANNEL: 'some-channel'
  PUBLIC_GITHUB_PAGE: 'github-page'
  PUBLIC_TWITTER_USERNAME: 'twitterUser'
  UPSTASH_REDIS_REST_URL: 'https://upstash.example.com'
  UPSTASH_REDIS_REST_TOKEN: 'ABC123'
jobs:
  test:
    name: Vite Tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install Node dependencies
        run: pnpm install
      - name: Check Format
        run: pnpm run check:formatting
      - name: Check CSS
        run: pnpm run lint:css
      - name: Lint
        run: pnpm run lint
      - name: Check Svelte
        run: pnpm run check
